version: "3"
services:
  nginx:
    build: 
      context: ./nginx
    links:
      - web-node
    ports:
      - "80:80"
  web-node:
    build:
      context: ./app
    ports:
       - "3000:3000"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    links: 
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.110
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
  mysql:
   #找到當前目錄下mysql構建鏡像
    build: ./mysql
    #鏡像名稱
    image: compose-mysql:skill
    #項目名稱
    container_name: compose-mysql
    #端口映射
    ports:
     - "3306:3306"
     #將mysql目錄映射到本地 應根據自己所需要映射的目錄進行修改
    volumes:
     - "/Volumes/Mac Disk/Users/AllenWang/work/development/DB/mysql/conf:/etc/mysql/conf.d"
     - "/Volumes/Mac Disk/Users/AllenWang/work/development/DB/mysql/logs:/logs"
     - "/Volumes/Mac Disk/Users/AllenWang/work/development/DB/mysql/data:/var/lib/mysql"
     
    #設置編碼格式
    command: [
           '--character-set-server=utf8mb4',
           '--collation-server=utf8mb4_unicode_ci'
    ]
    #設置初始化密碼
    environment:
     MYSQL_ROOT_PASSWORD: "root"
  redis:
    image: redis
    ports:
      - "6379:6379"
      